### ISSUE TITLE
Clicking on "Create Map" from the Posts view on Crowdmap doesn't do anything

### ISSUE THREAD

**Issue by nargz503** [ushahidi/pingapp#119]
I posted something, and then clicked Create Map, nothing happens. Is that intended behavior, as in that create map functionality is not yet built? Thanks! 

See screenshot to get a clear understanding of what page I'm on 
![screen shot 2014-03-22 at 12 53 52 pm](https://f.cloud.github.com/assets/6730209/2491770/ed980ff0-b1fb-11e3-9945-0b89d386fc20.png)

**Comment by nargz503** [comment]
It appears that you cannot create a map unless you are logged in.

**Comment by aoduor** [comment]
Hey Anarghya,

Would be great to migrate any crowdmap related issues to https://GitHub.com/Ushahidi/crowdmap-issues/issues instead of here :)

**Comment by brianherbert** [comment]
For what it's worth, we're going to have a total design overhaul which should clear up issues such as these in the next couple weeks.

**Comment by nargz503** [comment]
Ah my bad @aoduor , don't know why/how I ended up in the ping section! And that's great @brianherbert :)
