### ISSUE TITLE
include_once(/Users/gregor/Projects/pingapp/httpdocs) failed to open stream: No such file or directory

### ISSUE THREAD

**Issue by gr2m** [ushahidi/pingapp#33]
I've setup a twilio account and put in the creds into `sms.php`. But now I get the error

![screen shot 2013-09-27 at 11 56 16](https://f.cloud.github.com/assets/39992/1224691/b6174944-2752-11e3-8133-5082fc9bcb47.png)

**Comment by ekala** [comment]
@gr2m Install the dependencies in the `composer.json` file. See **Downloading** section in the README

**Comment by gr2m** [comment]
yes, it was a composer problem, good now, cheers
