### ISSUE TITLE
Validation message when creating a contact without phone number is unhelpful

### ISSUE THREAD

**Issue by alxndrsn** [ushahidi/pingapp#40]
When submitting contact without phone number, validation message: "invalid contact item"

Expected behaviour: message should give specific details about why it is invalid
![Uploading pingapp_validation_message.png . . .]()

**Comment by alxndrsn** [comment]
![pingapp_validation_message](https://f.cloud.github.com/assets/191496/1225257/acb211b8-2761-11e3-8936-3244707042c4.png)

**Comment by dkobia** [comment]
Closed by 147ba7056307ece701ed7ff49c0160c6c0accb0d
