### ISSUE TITLE
Navigation Cleanup

### ISSUE THREAD

**Issue by dkobia** [ushahidi/pingapp#57]
Hey @middle8media -- need some help cleaning up navigation. Its a little confusing moving back and forth through the system at the moment. Would foundation breadcrumbs suffice? Do we need different menu placement?

**Comment by sethburtonhall** [comment]
Yes, breadcrumbs could be a good fit for this. Go ahead with that and then let's see how if fits.

Don't forget about the semantic grid living in the `.scss` files

this should suffice ...

.breadcrumbs {
    @include grid-column(12)
}
