### ISSUE TITLE
Add TOS and Privacy links to footer

### ISSUE THREAD

**Issue by dkobia** [ushahidi/pingapp#95]
@middle8media ... Possible to add the 'made by ushahidi' logo graphic as well?

**Comment by sethburtonhall** [comment]
Yes

**Comment by sethburtonhall** [comment]
The footer is complete on my local repo. I am not sure the logo is needed. A basic text copyright seems more appropriate.

I am waiting to resolve an push conflict before the commit can be seen.

**Comment by dkobia** [comment]
@middle8media let me know if I can help with resolving that merge conflict.
